### ISSUE TITLE
help with a quote

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/paper#108]
It is the technology that we do not control the one that is used to control us.
Emiliano Kargieman, space hacker (1975)

**Comment by SFSandra** [comment]
To my parochial English ears this quote isn't quite making sense.  I know what it means ....but the up words mixed seem. :-D Wanted to check am I the only one stubbing my linguistic toe on this?

**Comment by santisiri** [comment]
i think you corrected it okay. the original is in spanish.

**Comment by medied** [comment]
Yea I think I see where you are coming from @SFSandra. Earlier I created PR #76 regarding that quote, just a small tweak. I think it just sounds funny because the original is in spanish.
