### ISSUE TITLE
Guidelines for Contribution

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/paper#111]
For when the community comes in : 
a. how to make contributions
b. deadline for contributions
c. DEF process for handling/responding (good for contributors as well as us to be clear on)
--> Maybe a sovereign instance can help is that.

It could be a text set by default on Github by putting the md file ISSUE_TEMPLATE.md at the root of the repo.

**Comment by santisiri** [comment]
definitely we must have this! great idea @virgile-dev

**Comment by virgile-dev** [comment]
Did it for Sovereign :) https://github.com/DemocracyEarth/sovereign/pull/194
Could be cool to have PR guide also. 
Let's see how we can adapt this to the whole open source paper thing.

**Comment by virgile-dev** [comment]
Here is the pull request for it :) https://github.com/DemocracyEarth/paper/pull/122
