### ISSUE TITLE
Something off about this sentence?

### ISSUE THREAD

**Issue by medied** [DemocracyEarth/paper#113]
I've re-read this sentence a few times and something about it seems off. I was going to create a PR but I'm actually not sure what it meant by it, so thought I would check in here with an issue. 

> Electronic voting: proposals that deliver solutions based on electronic voting machines aim to secure the process through a digital interface yet with the same logic of few elections per year, i.e. legitimizing professional politicians is served.

Specifically: "_i.e. legitimizing professional politicians is served_". Should I read that as "legitimizing _how_ professional politicians _are_ served" or "legitimizing professional politicians _as_ served". Am I the only one who thinks the current state of the sentence reads funny?

**Comment by SFSandra** [comment]
Yes that's a bit awkward....my rewrite is a little wordier - feel free to hack away: 

Electronic voting: proposals that deliver solutions based on electronic voting machines aim to secure the process through a digital interface but without changing the practice of holding only a few elections per year, with the net effect  new technology serving the same old anti-democratic purpose of legitimizing professional politicians as old voting technology.

**Comment by santisiri** [comment]
go ahead with a PR.

**Comment by medied** [comment]
Alright will PR now
