### ISSUE TITLE
"surveillance capitalism"

### ISSUE THREAD

**Issue by GaspardJ** [DemocracyEarth/paper#119]
I think the expression "surveillance capitalism" (1.5 Decentralization) is ideologicly stamped and doesn't serve the academic prupose of the paper.

I think "surveillance society" would convey the same idea without the anti free market taste of it.

**Comment by virgile-dev** [comment]
Yeah I agree. 
I really like how Naval Ravikant explains this at the blockstack summit : https://youtu.be/IrSn3zx2GbM?t=10m34s

I'm making a PR changing to surveillance society. 

Thanks @GaspardJ and welcome to the crew :)

**Comment by virgile-dev** [comment]
there goes the pul request : #120
