### ISSUE TITLE
Regarding the timeline image in Contributing.md

### ISSUE THREAD

**Issue by medied** [DemocracyEarth/paper#128]
Hey @virgile-dev, really like that you got Contributing.md started. You mention in there that this OS paper is a 'living document that can be constantly updated and amended', which I like, constitution imagery and all. 

![screen shot 2017-08-15 at 2 03 28 pm](https://user-images.githubusercontent.com/4752599/29336684-7411213a-81c3-11e7-9541-fd614f27db2b.png)

Would you say it makes sense replace to 'Finalized version' above with something else? The word 'finalized' seems to contradict what we say earlier about it being a living document. Maybe switch it to 'Version 1.0 ready' or something like that?

**Comment by virgile-dev** [comment]
Hey @medied what about **v1 stable**
