### ISSUE TITLE
Last Paragraph End game

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/paper#163]
I love the ending!  But I noticed today that it was altered a bit, the verbiage of "the next SV" morphing to "the next America".  Would love to hear why the change.... also want to make a case for keeping the place referent SV and not America - I wouldn't want this paper to exclude readers who justifiably resent and/or fear America, whose numbers are probably legion at this point.  I realize the intent is to evoke the spirit of the creation of America, and its promise...which is why I think the SV referent is the one to keep, metaphorically speaking :-)  

Would like to hear preferences from the team on the last sentence @piamancini @santisiri @paulamlb @herbstephens @virgile-dev  - keep the current, or adopt (and/or edit) the new?

Current
Such is the consequence of disintermediation of trust without boundaries, and this reality won't emerge on a single isolated region of the planet but rather distributed accross the whole globe. The next America is not in a far out land but the internet itself rising as the one true open, free and sovereign network of peers.

New
Such is the remarkable consequence of disintermediation of trust without boundaries, a reality that won't emerge in a single isolated part of a country or region of the globe, but will be distributed across the entire planet. The "next Silicon Valley" is not in a far away land or _on_ any land at all, but a new frontier of the internet itself rising as the one true open, free and sovereign network of peers.

**Comment by santisiri** [comment]
I see what you mean @SFSandra. I will edit this right now since I have the editor open here and include your version for it.

**Comment by SFSandra** [comment]
It's a very satisfying ending to the paper, kudos for writing it!
