### ISSUE TITLE
Democratic Welfare Fund - clarifications needed

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/paper#167]
Whatever else we decide, I strongly strongly recommend calling this a Democracy Support Fund, and not use the word WELFARE which has all sorts of implications that are at odds with, or will cloud, our actual focus.

**Comment by SFSandra** [comment]
A further question: 


One: We expect that the Democratic Welfare Fund becomes a public resource managed via global governance. 

It seems we are saying that the money we raise from the 10 million tokens sold will be democratically managed by those who have votes, and initially, that is us, and we are saying 70%/15%/15% as described. Makes sense.  But over time how do we manage token holders' votes to manage?  This obviously requires us to have a programmatic approach to raising issues to vote for budget allocation in regular time interviews, transparent and accountable.   We better get busy designing this so we are eating our own dog food from the beginning on this!

Two: The Democracy Earth Foundation will work to engage donors of all kinds, including state-actors, institutions and individuals, to allocate at least 5% of their donating capacity to be managed by a legitimate global vote. We hope to provide a path for the sustainability of organizations able to execute projects focused on pressing issues. 

Does this belong in the white paper, justifying raising funds in an ICO?   We will work with many different types of partners like High Fidelity and Aragon to create software that will help solve some of the intractable problems we've identified......but this is talking about collecting *additional* funds from *additional* players in order fund projects outside the scope of software development.  It is certainly a good purpose for DEF to adopt, but not sure it belongs in the white paper which is focused on how we create software/technology solutions.

**Comment by santisiri** [comment]
Hi @SFSandra, I have been discussing this with @herbstephens. I think you get it right and our aim is to enable a commons beyond the strict control of any single organization. This is not a matter for a document aside from the paper since it has to do with our funding mechanism. I'm okay with modifying the name of the fund.

**Comment by SFSandra** [comment]
I should have separated the issues into 2 separate posts -sorry. 

#1 Introducing the idea of governance by token holders will probably raise questions as to how/when we'll enact this, and I was thinking this is probably something people would expect us not to be vague about, given it's a case of eating our own dog food, so to speak.

**Comment by SFSandra** [comment]
#2  "we will engage donors of all kinds, including state-actors, institutions and individuals, to allocate at least 5% of their donating capacity to be managed by a legitimate global vote". 

Put another way we are saying DEF is raising ICO funds at least in part, to raise a fund from all kinds of donors to fund "projects focused on pressing issues" chosen by global vote.  

For me, this is taking focus away from the funding mechanism and introducing a lot of questions about how these additional funds.
