### ISSUE TITLE
Adding Colombia's use case on peace referendum 

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/paper#176]
A friend I sent the paper to told me that a concrete use case of Sovereign would make things more concrete for him.

How do you guys feel about adding something about _Plebiscito Digital_ which I argue is quite solid as [OECD made a report](https://www.oecd.org/gov/innovative-government/embracing-innovation-in-government-colombia.pdf) about it ? 

If yes, how do you suggest it's best that we include it : 
- a section ? 
- just a small ref and a link ? 
- an annex ?

**Comment by SFSandra** [comment]
I tend to agree w/ your friend -- I'll have a section for team review shortly!

**Comment by virgile-dev** [comment]
Hey @SFSandra thanks a lot for the write up. Here are a couple edits I'd add : 

2.3.4 Liquid Democracy: A Use Case
“Blockchain could disrupt voting, just as it has currency, and could apply to any democratic government.” ~ The Organization for Economic Cooperation and Development

In October 2016, following a shocking, almost universally unexpected No to peace in the Colombian referendum that put at risk years of negotiation between the government & the marxist narco-guerrillas,Democracy Earth piloted the Sovereign liquid democracy platform in a [digital plebiscite](http://plebiscitodigital.co/) enabling a symbolic vote among the diaspora of ~6 million expatriate citizens. Instead of giving a voter the binary option, the pilot enabled people to vote separately on seven separate sub-themes of the proposed treaty, as well as to delegate their votes to more knowledgeable voters, with results revealing important nuances in voter preferences not captured in the referendum, including the [deal breaker that emerged](https://words.democracy.earth/a-digital-referendum-for-colombias-diaspora-aeef071ec014): an overwhelming “No” among pilot participants to one particular statement of the treaty regarding political participation of the FARC.

![colombia](https://user-images.githubusercontent.com/11473995/30007342-aeb681b0-910c-11e7-900a-a89b1d96b960.png))

The pilot study had the [additional impact](https://www.oecd.org/gov/innovative-government/embracing-innovation-in-government-colombia.pdf) of increasing the media and political profile of blockchain-enabled liquid democracy in Colombia; a blockchain-savvy political party has sprung up, the Partido de la Red Colombia party (“The Net Party”), while the Colombian government’s Centre for Digital Public Innovation (CDPI) investigating the technology as well.

**Comment by SFSandra** [comment]
thanks @virgile-dev! I made a couple more edits too ..

**Comment by santisiri** [comment]
Hi guys, this looks great. Happy with the write up. I was thinking maybe an annex/appendix with the use cases would be more helpful.. we can keep extending the paper with this cases in the future without disrupting the flow of the overall text that way. 

what do you think?

**Comment by virgile-dev** [comment]
For the sake of making it more concrete real to users,  I think It'd be good to add this as a section. 
I suggest we treat The colombian use case as our flagship use case which justify its presence in the body of the paper.
When we implement more use cases we can create an annexe where to list them, we would then use the Colombian use case section to point to it. "More Sovereign use cases in Annexe 1" for instance.

**Comment by santisiri** [comment]
Go ahead.

**Comment by herbstephens** [comment]
Agree.  Appendix of use cases great idea... can keep adding.

__________________________________________________________________________
