### ISSUE TITLE
Using github release feature 

### ISSUE THREAD

**Issue by virgile-dev** [DemocracyEarth/paper#179]
@santisiri What do you think of making using the [release feature of Github](https://help.github.com/articles/creating-releases/) to announce a 0.1 release of the paper ?

That we could label a branch as 0.1 stable and work on evolutions with the community on the master branch.

**Comment by santisiri** [comment]
Great idea my friend! On it.

**Comment by virgile-dev** [comment]
Nice ! I'm re-reading the whole thing today I'll send a few fixes (typos and things like that) and we can make the release tomorow (Big day ;) )

**Comment by santisiri** [comment]
Just did it. :) 

Still, feel free to keep contributing!

**Comment by virgile-dev** [comment]
Oh snap, it's already done !
Yep, onto 0.1.1 then haha
