### ISSUE TITLE
No mention of BitNation ?

### ISSUE THREAD

**Issue by domi41** [DemocracyEarth/paper#203]
https://bitnation.co

We see a few places where a mention might be relevant. _(decentralised identity)_ Do you ?

**Comment by santisiri** [comment]
i don't think necessarily decentralised identity is a bit nation thing. it's a very widely discussed topic. i think they're doing a good amount of experimentation which is interesting to follow. but our core is voting and in that respect the current bibliography of paper (clearly listed on the paper) is a very good resource specifically on that.

**Comment by domi41** [comment]
Ooooh ! Never saw the bibliography on the pdf, good stuff there, thanks !
