### ISSUE TITLE
Remove merged branches

### ISSUE THREAD

**Issue by roipoussiere** [DemocracyEarth/paper#213]
There are many, many branches in the repo and it begins difficult to say which one is useful or not. It would be clearest to remove all merged branches. :)

**Comment by domi41** [comment]
Well spotted, thanks !
We did some cleanup of merged branches and old closed branches.

@SFSandra There are two branches, `fr` and `zh`, that we're not using. Can we close them ?

**Comment by medied** [comment]
Yes good idea @roipoussiere, we can start cleaning up there. I'm gonna go ahead and close some, @domi41 feel free to do the same
