### ISSUE TITLE
Problem in the Spanish Version

### ISSUE THREAD

**Issue by ValentinaValentini** [DemocracyEarth/paper#263]
![capture d ecran 2017-10-10 a 20 54 03](https://user-images.githubusercontent.com/32238352/31404774-47ebc02c-adfd-11e7-86b6-d9f058e7933a.png)

Just stumbled upon this:

In the 2.3.2 Delegations section, the translated version is missing and has inadvertently been replaced by a replica of the previous paragraph.

**Comment by SFSandra** [comment]
thanks for the catch!

**Comment by medied** [comment]
Thanks for catching this @ValentinaValentini, fixed with 68008ef109ce964bff42624f2260af4f4b7a21b5
