### ISSUE TITLE
Translation to Swedish

### ISSUE THREAD

**Issue by se37301** [DemocracyEarth/paper#309]
Hi there, I want to help you guys with translation of 'README.mediawiki' text to Swedish language.

**Comment by SFSandra** [comment]
Thank you, it will be amazing to have a Swedish translation!

**Comment by se37301** [comment]
I have made two updates in as "pull request" - I have made a "rough" first translation of all chapters. There will be a need to adjust it and get a second oppinion from other Swedish speaking peers. 

The translation process in Google translate showed to be really really good - I was amazed.
However I did some minor adjustments to the Swedish "lingo" and sentences. 
I do have some words and phrases that needs to get a decision in selection of appropriate wordings.

I enjoyed reading the material and also learned new stuff from that.
