### ISSUE TITLE
“Consciousness is the new political frontier being drawn” -  Dwight's concern

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/paper#32]
from DW:  

> “Consciousness is the new political frontier being drawn.” 

That’s one of those big statements I am drawn to – and I liked it last week – but now I really wonder what it means, and suspect it could wind up meaning lots of different things to lots of different people.  Does it really help move things forward?

**Comment by SFSandra** [comment]
This issue is actually Dwight's, I am merely posting for him.  FWIW I don't consider it an issue for the statement to potentially mean different things to different people, and in fact consider it a hallmark of all great writing about great human endeavor.

**Comment by paulamlb** [comment]
My 0.02 is that it would be wonderful to explore this idea a little more, because:
A - it's a great idea to be explored
B - manages interpretation

**Comment by santisiri** [comment]
i think dwight needs to read 'homo deus' from yuval harari. i included some unpacking into that expression in the a.i. section today.

**Comment by SFSandra** [comment]
omg yes - read this just the other day: 

Q by Helen Czerski, physicist: We are living through a fantastically rapid globalisation. Will there be one global culture in the future or will we maintain some sort of deliberate artificial tribal groupings?

A by Yuval Harari: I’m not sure if it will be deliberate but I do think we’ll probably have just one system, and in this sense we’ll have just one civilisation. In a way this is already the case. All over the world the political system of the state is roughly identical. All over the world capitalism is the dominant economic system, and all over the world the scientific method or worldview is the basic worldview through which people understand nature, disease, biology, physics and so forth. There are no longer any fundamental civilisational differences.

**Comment by dwightmwilson** [comment]
Thx Sandra, I like the Harari quote and would agree with it about 90% or so.  Eventually we'll truly have a majority of the world that's grown up and come of age with a mindset that says we are all one, we need one system, we need a way that are all on the same playing field, etc. But...I still would not say that the quote talks to consciousness per se - and 'consciousness' can mean so many things to so many different people. We have 20+ pages of fabulous stuff already in the whitepaper, I'm just not sure this adds anything major that we have overlooked or that investors will flock to in big ways.

**Comment by SFSandra** [comment]
yeah @dwightmwilson I'm not really recommending that this quote be included in the white paper, I was just reinforcing Santi's comment above

**Comment by SFSandra** [comment]
Hey @paulamlb we should def do a Medium post on this topic, let's discuss! (re: consciousness as the new political frontier)
