### ISSUE TITLE
Pegging 1 vote to 1 hour of work

### ISSUE THREAD

**Issue by jamesray1** [DemocracyEarth/paper#347]
![screenshot from 2018-02-12 13-31-53](https://user-images.githubusercontent.com/16969914/36081972-1a9bd6bc-0ff9-11e8-9d87-2e5cb5821610.png)

There are a few issues with pegging 1 vote to 1 hour of work. If you peg it to the USD, it doesn't account for differences in the minimum wage between countries. For instance in Australia, the minimum wage is about 22 AUD. While in developing countries, the minimum wage will be lower. So it may be better to peg one vote to the minimum wage in fiat of one's jurisdiction, similar to Chronobank.

**Comment by herbstephens** [comment]
The vote token is not being pegged to the USD - only the initial price is set relative to an hourly wage based in USD.  Otherwise, the value will be market-based.

**Comment by jamesray1** [comment]
Ah, OK.

**Comment by jamesray1** [comment]
Although regarding ICOs, there are some other novel ways that could be better, although maybe it's a bit late (but not too late) to implement them.

https://ethresear.ch/t/daico-and-iterative-investment/1052
https://github.com/DemocracyEarth/paper/blob/master/README.mediawik

**Comment by Tasty213** [comment]
Is this issue closed now @jamesray1 ?
