### ISSUE TITLE
Reference to Easter Island in section 3. Execution is racist and contradicts the name 'DemocracyEarth'

### ISSUE THREAD

**Issue by willscire** [DemocracyEarth/paper#363]
In the Pacific, Easter Island, more authentically known as Rapanui, is not a far away land. Of course colloquially it might be nicknamed a "far away land" due to its other name Te Pito o Te Henua which more or less translates to "The End of The Earth", however today such statements are false and no longer true.
Internet media is omnipresent to every place on Earth and viewers of this GitHub account that reside on Rapanui have direct and immediate access to this living document at the instant that it is updated, and are therefore not "far away". Rapanui is not an exotic fairyland idea to be bandied about by the whims of people that have most probably never had any true connection to the place. It is a real place with real human beings with living history that are working right now every day to live real lives.

**Comment by combinatorist** [comment]
I strongly agree with @willscire and attempted to fix this with #383.
