### ISSUE TITLE
The paper is too long and not easy to understand

### ISSUE THREAD

**Issue by xtosis** [DemocracyEarth/paper#374]
I want to make it shorter, more organised and easier to understand so that we can get more people in on this. I'm good at this sort of thing. Should I finish editing at one go or should I go section by section, request a pull request, wait for you guys to approve then proceed to the next section? Example:

Original Abstract (334 words):
> In a world that has succeeded in the globalization of financial assets while keeping political rights enclosed to territories, we need to build new models of democratic governance that enable humanity to collaborate and address pressing global issues. Democracy Earth Foundation is building free, open source software for incorruptible blockchain-based decision-making (voting) within institutions of all sizes, from the most local involving two people to the most global involving all of us. Uneven distribution of opportunity around the globe due to the perpetual confrontation between national governments has led to accelerated climate change, rising inequality, terrorism and forced migrations. Democracy Earth Foundation considers that the technology stack that includes Bitcoin as programmable money without Central Banks, and Ethereum enabling smart contracts without the need of Judiciary Courts, requires a new layer that signals incorruptible votes beyond the territorial boundaries of Nation-States. This transnational network will act in accordance with the personal sovereignty of its members and protect their human rights with encryption. In our Initial Rights Offering we offer a token called vote that will grant participation rights to every human with decision-making as its main function. Our proposal introduces cryptographically induced equality: as long as any person is able to validate his or her self-sovereign identity, they will receive a corresponding share of votes that is equal to the share of every active participant in the network. We define a Proof of Identity process that avoids central authority by introducing the concept of attention mining which incentivizes participants to strengthen the trust of votes by performing simple tests aimed at detecting replicants. Finally votes get dripped to valid participants under a Universal Basic Income mechanism with a goal of finding a proper equilibrium in the historical tension between money and politics. We seek nothing less than true democratic governance for the Internet age, one of the foundational building blocks of an achievable global peace and prosperity arising from an arc of technological innovations that will change what it means to be human on Earth.

New Abstract (214 words):
> Current Oligarchical Nation-State Governments (ONSG) fail to eliminate corruption, and not only do they usually fail to reduce the uneven distribution of opportunity and wealth, but often even contribute to it or enable it. Furthermore, they also fail to effectively address pressing global issues such as climate change, war, mass migrations and are also notorious for failing to deliver what they promise. Democracy Earth Foundation aims to address these short comings by replacing ONSGs with a Direct Digital Democracy that is both free and open-source (i.e. transparent). The proposed system implements a distributed/de-centralized structure with blockchain technology to ensure incorruptibility and transparency of the election process: nobody can alter the votes, and everybody can verify the integrity of the election results. The project also renders Central Banks obsolete by implementing a cryptocurrency system like Bitcoin with smart contract capabilities like Ethereum with the proposed Universal Basic Income (UBI) system that is designed to put an end to the cryptocurrency-wars, abolish unequal distribution of wealth and incentivize participation in the new political system.  In this White Paper we first discuss the motivations behind this project (Manifesto). Next, we elaborate on the how the system works, the practical concerns and the solutions to these practical concerns (Paper). Lastly, we discuss how they can be implemented (Execution).

**Comment by SFSandra** [comment]
Hi, thanks for reading The Social Smart Contract, expressing your concerns and taking the time to demonstrate what you are proposing.  The Social Smart Contract is an open source project and we welcome your contribution.  Before beginning such an undertaking, I'd like to share some information with you - our ambassador program is getting ready (in a matter of weeks) to launch a free online course that breaks down the key elements of the white paper, meant for the 'layperson' to understand the more complex concepts.  It might be wise to wait until this program is released so that you can review and decide if your concerns are addressed with that effort. What do you think?

**Comment by xtosis** [comment]
Thanks for your informative reply Sandra. Yes I think I will wait.
