### ISSUE TITLE
Automation is not a bad thing

### ISSUE THREAD

**Issue by xtosis** [DemocracyEarth/paper#375]
In the manifesto there is a line that  deems automation as a bad thing that is happening under Nation-States:

> New forms of governance must acknowledge the networked commons connecting humanity and progressively weaken the legacy of national frontiers and its inherent inability to address pressing global issues such as climate change, rising inequality, terrorism, **automation** and forced migrations.

While I agree that when the pursuit of profit is God (capitalism) technology enslaves us and puts us out of our jobs but if that is not the case (Socialism/Communism) it actually sets us free. What we are doing here is an example of how technology and automation helps us. We could fully automate logistics, agriculture, construction and other routine, mundane or dangerous jobs to give us more time to do more interesting things.

**Comment by SFSandra** [comment]
I understand your point, and agree -  automation is not in and of itself a bad thing..which is why we list it as a pressing global issue, and not an out and out negative. Perhaps we should explicitly link automation to the negative issue we had in mind, which is joblessness.

**Comment by xtosis** [comment]
Well I believe it's merits should be emphasized as well or even more because should what we are trying to do here succeed, we will need a lot of it to provide everyone's basic needs such as food, water, utilities and e.t.c. I'll close issue for now but I'll get back to it perhaps in a later stage of this project.
