### ISSUE TITLE
It's too long.

### ISSUE THREAD

**Issue by paulamlb** [DemocracyEarth/paper#57]
I think we have all contributed and expressed our ideas fully onto this paper and I totally understand that doing that is a part of the process, but I think now is the time to be a little ruthless in the effort to make it more concise. I pasted it on word and it had 52 pages. It is too important to be this long, we want this to be widely read, to reach all corners of the earth and make waves. For that purpose, I would suggest 25 pages maximum. 

**I am positive that it is possible to be done without leaving any key information out.** But it will take both effort and detachment. I urge everyone to look into what they wrote and:

A- Shorten sentences. It's amazing how much you can achieve just by doing this, and it always sounds so much better afterwards. 

B - Check if one of the ideas wasn't mentioned in another part of the paper ( there are many times where the importance of decentralization and sovereignty is written about, for example ). There's no need to repeat things, it's better to be concise and say everything just once. 

C- Ask themselves if that piece of information in particular is absolutely relevant and the goals of the whitepaper would not be achieved without it. If not, DON'T DISCARD: save it somewhere for a future Medium post ;)

**Comment by SFSandra** [comment]
I'm eyeballing the Secrecy section - does it need to stay?

**Comment by paulamlb** [comment]
I have just shortened and merged the two sections that I had worked on - right versus debt and UBI. Although I think this one in particular needs to expand with implementation details, so it's good that I have already saved some space!

**Comment by paulamlb** [comment]
A couple suggestions: Background (1.1) can become About (5), and Gepolitics and Land vs Cloud could be merged.

**Comment by SFSandra** [comment]
For the sake of reference, the Aragon white paper is 39 pages long.

**Comment by santisiri** [comment]
Bitcoin's paper is 9 pages long.

But we are tapping on something huge. I'm not scared of a long paper here. It's a manifesto really.

**Comment by santisiri** [comment]
Had an idea:

Section 1: Manifesto
Section 2: Paper

Section 3 (to be done): Plan / Revolution?

**Comment by paulamlb** [comment]
I reeeeeally like this idea!!!

**Comment by mairwilliams** [comment]
The issue of getting a shorter, more down-to-earth text out of this keeps coming up and it's reasonable and desirable. I also love texts that carefully unpack the philosophy and vision behind a technology.

**Comment by SFSandra** [comment]
I like the idea of 3 sections (and I like the idea of publishing the 3 sections in one hardcover book).

**Comment by santisiri** [comment]
Fixed and included contents section. https://github.com/DemocracyEarth/paper/commit/e59b90d81cfb870d4fd79fb56ef6067f93bcb790

It's likely it will become a book too.

**Comment by SFSandra** [comment]
Your brother should illustrate, @santisiri !

**Comment by virgile-dev** [comment]
@SFSandra that is a wonderful idea !

**Comment by paulamlb** [comment]
Amazing! My point was referring to the entire document as a paper, but I totally agree with your points @mairwilliams and think dividing it between Manifesto / Paper / Plan was a GREAT solution!!
