### ISSUE TITLE
on the topic of organizational decision making

### ISSUE THREAD

**Issue by SFSandra** [DemocracyEarth/paper#78]
Aragon gave a shout out to DEF in *their* white paper because of the natural partnership between organizing and decision making i.e just as we are bringing liquid democracy to Aragon's organization platform, they are bringing organization to our liquid democracy. 

Are we touching on this in the white paper? Should we?

**Comment by santisiri** [comment]
Yes, think we should and I know exactly where i have Aragon in mind to use as example.

**Comment by SFSandra** [comment]
@herbstephens @santisiri  given Luis' enthusiasm maybe DEF and Aragon co-write a Medium post on 50/50 org, or UX (3 modes)?
